### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by ml-currenxie** [robert8888/react-tour-guide#6]
What is the best way to wait for a modal to work before looking for the selector?  

I tried using onBeforeShow to fire an action to open the modal, however it renders (and looks for selector) before the modal has been opened.

**Comment by robert8888** [comment]
First, sorry for the late reply. I feel guilty about it

if you want block go to next step and make some action before showing next step you can block next step by adding approval attribute.
```jsx
        const secondStepPromiseResolver = useRef();

        <Step
            key={"Step_2"}
            placement={"top"}
            selector={"[data-rtg-search-input]"}
            approve={{
                lock: true, // this blocking and wating for promise resolve
                promise: () => new Promise((res)=> {
                    secondStepPromiseResolver.current = () => res(); // setting promise resolve out of step to have control over it
                })
            }}
        >
            <p></p>
        </Step>
```

So in code above if you set a promise which will be resolved after 500 ms ? or what delay you need to show modal, then after this it will start preparing next step  by firing onNext -> then is fired onLock hook witch can block showing next step if not -> fired onBefoerShow and immiedtliy loooking for selector and starting prepering next step. 

[Tour component](https://github.com/robert8888/react-tour-guide/blob/master/src/lib/components/Tour/Tour.js#L342)
```javascript 
        _step.props.onBeforeShow && _step.props.onBeforeShow();

        const target = document.querySelector(_step.props.selector);
```

You can try with onNext becase is fired earlier than onBeforeShow. But i'm not shure that this will be enoguth in your case. I created approve by promis to allow blocking next step as long as is need to preper some action (call to api or what ever).

I hope I understood your case correctly and if not you (due to answer delay), maybe it will help someone else.

**Comment by robert8888** [comment]
To meet you and probably other user needs I created better solution.

From 1.1 version i add wait attribute to Step component. Now we can add
```jsx
<Step wait={async () => awiat ....} />
```
or
```jsx
<Step wait={2000} onWait={(waiting) => console.log("wating status", waiting)}/>
```
```jsx
const [tour] = useTour("tourId")

tour.setWait({id: "step4", wait: 2000})
//or
tour.setWait({index: 3 wait: 2000})
//and then
tour.on("wait", ({index, state, id}) => {
    state
        ? console.log(`on wait for step ${index}`)
        : console.log(`on finish waiting for step ${index}`)
})
```

This will block going to next step, and lookup for selector until passed promise will be resolved or given time will run. 

This can be halpfull wen we need wait for some api data or apearing some element in DOM tree.  

I updated docs and i closing this thread. If anybody will have problems / question feel free to ask reopen this, or crate new issue.
